FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

# Install project deps
COPY pyproject.toml .
RUN pip install --no-cache-dir \
    mlflow==3.8.1 \
    psycopg2-binary \
    boto3 \
    pandas \
    scikit-learn

# Copy training code
COPY src/ src/
COPY data/ data/

CMD ["python", "-m", "src.train_baseline"]
