FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install --no-cache-dir \
    mlflow==3.8.1 \
    psycopg2-binary \
    boto3 \
    fastapi \
    uvicorn \
    pandas \
    scikit-learn

COPY inference_api.py .
COPY features.json .
COPY src/ src/

EXPOSE 8000

CMD [  "uvicorn",  "inference_api:app",  "--host", "0.0.0.0",  "--port", "8000"]
