FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    pydantic

COPY inference_api.py .
COPY features.json .

EXPOSE 8000

CMD [  "uvicorn",  "inference_api:app",  "--host", "0.0.0.0",  "--port", "8000"]
